### ISSUE TITLE
Помогите. Не могу скомпилировать Demo проект

### ISSUE THREAD

**Issue by kapkapas** [d-mozulyov/Tiny.Rtti#3]
Добрый день! Дмитрий, помогите.  Не могу скомпилировать демо-проект 
...\Tiny\demo\InvokeBenchmark\InvokeBenchmark.dproj
[dcc32 Error] Tiny.Rtti.pas(13594): E2045 Bad object file format: '...\Tiny\objs\win32\tiny.rtti.o'

Вы сделали замечательную вещь... Спасибо.

**Comment by d-mozulyov** [comment]
Здравствуйте. А какая у Вас версия компилятора?

**Comment by d-mozulyov** [comment]
Возможно дело в том, что у Вас не установлено расширение LFS для Git. Размер файла tiny.rtti.o должен быть 23251 байт. 

Если это не так, то попробуйте в командной строке в папке проекта выполнить команду
> git lfs install

А потом
> git lfs pull

**Comment by kapkapas** [comment]
Embarcadero RAD Studio 10.2. Соотв. версия компилятора 32.0

**Comment by kapkapas** [comment]
> 23251 байт.
Конечно, не такой :-(

**Comment by kapkapas** [comment]
> Если это не так, то попробуйте в командной строке в папке проекта выполнить команду
> git lfs install
Как бы скачать... Я пользуюсь git через браузер...

**Comment by d-mozulyov** [comment]
Думаю, можно скачать напрямую в браузере: https://github.com/d-mozulyov/Tiny.Rtti/blob/master/objs/win32/tiny.rtti.o
Но я бы рекомендовал пользоваться Git
