### ISSUE TITLE
Demo c Vcl

### ISSUE THREAD

**Issue by kapkapas** [d-mozulyov/Tiny.Rtti#5]
При компиляции демо примера (опять с производительностью Invoke - InvokeBenchmark) в Vcl-проекте (с Fmx все нормально) возникает ошибка
First chance exception at $007FC485. Exception class $C0000005 with message 'access violation at 0x007fc485: read of address 0x00000000'. Process Project3.exe (10316)
Это вход в метод 

function TVmtMethodExEntry.GetData(var AData: TSignatureData): Integer;
var
  LEntry: PVmtMethodEntry;
  LSignature: PVmtMethodSignature;
begin
  LEntry := Entry;                                   /// <---- Здесь 
  if (Assigned(LEntry)) then
  begin
    LSignature := LEntry.Signature;
    if (Assigned(LSignature)) then

**Comment by kapkapas** [comment]
### При компиляции - Вай .... 6(((
При работе демо примера InvokeBenchmark

**Comment by d-mozulyov** [comment]
Здравствуйте

Благодарю за обратную связь. Я правил похожий баг около месяца назад. Ждите релиза

**Comment by d-mozulyov** [comment]
Произошёл релиз. Просьба проверить

**Comment by kapkapas** [comment]
Спасибо, обязательно посмотрю внимательно завтра

**Comment by d-mozulyov** [comment]
Ну что в итоге?

**Comment by kapkapas** [comment]
Ok
